import type { Metadata } from 'next';

import './globals.css';

import { cn } from '@/lib/utils';

import { adventPro, capriola, dancingScript, fontSans } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
          capriola.variable,
          adventPro.variable,
          dancingScript.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
